/**
 * Comprehensive food database with accurate nutrition data
 * All values are per 100g serving unless otherwise specified
 */

import { FoodDatabaseEntry, FoodItem } from '@/types';

export const foodDatabase: FoodDatabaseEntry[] = [
  // Proteins
  {
    id: 'chicken-breast',
    name: 'Chicken Breast',
    category: 'Proteins',
    servingSize: '100g',
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    sugar: 0,
    sodium: 74,
    tags: ['poultry', 'lean', 'high-protein', 'grilled', 'baked'],
    commonPortions: [
      { label: 'Small (100g)', multiplier: 1 },
      { label: 'Medium (150g)', multiplier: 1.5 },
      { label: 'Large (200g)', multiplier: 2 },
    ],
  },
  {
    id: 'chicken-thigh',
    name: 'Chicken Thigh',
    category: 'Proteins',
    servingSize: '100g',
    calories: 226,
    protein: 25,
    carbs: 0,
    fat: 15,
    fiber: 0,
    sugar: 0,
    sodium: 84,
    tags: ['poultry', 'dark-meat', 'grilled', 'baked'],
    commonPortions: [
      { label: '1 thigh (120g)', multiplier: 1.2 },
      { label: '2 thighs (240g)', multiplier: 2.4 },
    ],
  },
  {
    id: 'salmon',
    name: 'Salmon',
    category: 'Proteins',
    servingSize: '100g',
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    fiber: 0,
    sugar: 0,
    sodium: 59,
    tags: ['fish', 'seafood', 'omega-3', 'grilled', 'baked'],
    commonPortions: [
      { label: 'Small fillet (120g)', multiplier: 1.2 },
      { label: 'Medium fillet (150g)', multiplier: 1.5 },
      { label: 'Large fillet (200g)', multiplier: 2 },
    ],
  },
  {
    id: 'tuna',
    name: 'Tuna',
    category: 'Proteins',
    servingSize: '100g',
    calories: 132,
    protein: 28,
    carbs: 0,
    fat: 1,
    fiber: 0,
    sugar: 0,
    sodium: 47,
    tags: ['fish', 'seafood', 'lean', 'high-protein'],
    commonPortions: [
      { label: 'Can (150g)', multiplier: 1.5 },
      { label: 'Steak (170g)', multiplier: 1.7 },
    ],
  },
  {
    id: 'beef-steak',
    name: 'Beef Steak',
    category: 'Proteins',
    servingSize: '100g',
    calories: 271,
    protein: 26,
    carbs: 0,
    fat: 19,
    fiber: 0,
    sugar: 0,
    sodium: 58,
    tags: ['beef', 'red-meat', 'grilled'],
    commonPortions: [
      { label: 'Small (150g)', multiplier: 1.5 },
      { label: 'Medium (225g)', multiplier: 2.25 },
      { label: 'Large (340g)', multiplier: 3.4 },
    ],
  },
  {
    id: 'ground-beef-lean',
    name: 'Ground Beef (90% lean)',
    category: 'Proteins',
    servingSize: '100g',
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 15,
    fiber: 0,
    sugar: 0,
    sodium: 75,
    tags: ['beef', 'ground', 'lean'],
    commonPortions: [
      { label: '1/4 lb (113g)', multiplier: 1.13 },
      { label: '1/2 lb (227g)', multiplier: 2.27 },
    ],
  },
  {
    id: 'eggs',
    name: 'Eggs',
    category: 'Proteins',
    servingSize: '100g (2 large)',
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    fiber: 0,
    sugar: 1.1,
    sodium: 124,
    tags: ['breakfast', 'boiled', 'scrambled', 'fried'],
    commonPortions: [
      { label: '1 egg (50g)', multiplier: 0.5 },
      { label: '2 eggs (100g)', multiplier: 1 },
      { label: '3 eggs (150g)', multiplier: 1.5 },
    ],
  },
  {
    id: 'tofu',
    name: 'Tofu (Firm)',
    category: 'Proteins',
    servingSize: '100g',
    calories: 144,
    protein: 17,
    carbs: 3,
    fat: 9,
    fiber: 2,
    sugar: 0,
    sodium: 16,
    tags: ['vegetarian', 'vegan', 'plant-based', 'soy'],
    commonPortions: [
      { label: '1/4 block (100g)', multiplier: 1 },
      { label: '1/2 block (200g)', multiplier: 2 },
    ],
  },
  {
    id: 'shrimp',
    name: 'Shrimp',
    category: 'Proteins',
    servingSize: '100g',
    calories: 99,
    protein: 24,
    carbs: 0,
    fat: 0.3,
    fiber: 0,
    sugar: 0,
    sodium: 111,
    tags: ['seafood', 'shellfish', 'lean', 'grilled'],
    commonPortions: [
      { label: 'Small serving (100g)', multiplier: 1 },
      { label: 'Medium serving (150g)', multiplier: 1.5 },
    ],
  },
  {
    id: 'pork-chop',
    name: 'Pork Chop',
    category: 'Proteins',
    servingSize: '100g',
    calories: 242,
    protein: 27,
    carbs: 0,
    fat: 14,
    fiber: 0,
    sugar: 0,
    sodium: 62,
    tags: ['pork', 'grilled', 'baked'],
    commonPortions: [
      { label: 'Small chop (150g)', multiplier: 1.5 },
      { label: 'Medium chop (200g)', multiplier: 2 },
    ],
  },
  {
    id: 'turkey-breast',
    name: 'Turkey Breast',
    category: 'Proteins',
    servingSize: '100g',
    calories: 135,
    protein: 30,
    carbs: 0,
    fat: 1,
    fiber: 0,
    sugar: 0,
    sodium: 54,
    tags: ['poultry', 'lean', 'high-protein', 'thanksgiving'],
    commonPortions: [
      { label: '2 slices (60g)', multiplier: 0.6 },
      { label: '4 slices (120g)', multiplier: 1.2 },
    ],
  },

  // Vegetables
  {
    id: 'broccoli',
    name: 'Broccoli',
    category: 'Vegetables',
    servingSize: '100g',
    calories: 34,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    fiber: 2.6,
    sugar: 1.7,
    sodium: 33,
    tags: ['green', 'steamed', 'roasted', 'healthy'],
    commonPortions: [
      { label: '1 cup (91g)', multiplier: 0.91 },
      { label: '2 cups (182g)', multiplier: 1.82 },
    ],
  },
  {
    id: 'spinach',
    name: 'Spinach',
    category: 'Vegetables',
    servingSize: '100g',
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    sugar: 0.4,
    sodium: 79,
    tags: ['green', 'leafy', 'salad', 'healthy'],
    commonPortions: [
      { label: '1 cup raw (30g)', multiplier: 0.3 },
      { label: '2 cups raw (60g)', multiplier: 0.6 },
    ],
  },
  {
    id: 'carrots',
    name: 'Carrots',
    category: 'Vegetables',
    servingSize: '100g',
    calories: 41,
    protein: 0.9,
    carbs: 9.6,
    fat: 0.2,
    fiber: 2.8,
    sugar: 4.7,
    sodium: 69,
    tags: ['orange', 'raw', 'cooked', 'healthy'],
    commonPortions: [
      { label: '1 medium (60g)', multiplier: 0.6 },
      { label: '2 medium (120g)', multiplier: 1.2 },
    ],
  },
  {
    id: 'tomato',
    name: 'Tomato',
    category: 'Vegetables',
    servingSize: '100g',
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    sugar: 2.6,
    sodium: 5,
    tags: ['red', 'raw', 'salad', 'healthy'],
    commonPortions: [
      { label: '1 small (100g)', multiplier: 1 },
      { label: '1 large (180g)', multiplier: 1.8 },
    ],
  },
  {
    id: 'cucumber',
    name: 'Cucumber',
    category: 'Vegetables',
    servingSize: '100g',
    calories: 15,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    fiber: 0.5,
    sugar: 1.7,
    sodium: 2,
    tags: ['green', 'raw', 'salad', 'refreshing'],
    commonPortions: [
      { label: '1/2 cup (50g)', multiplier: 0.5 },
      { label: '1 cup (100g)', multiplier: 1 },
    ],
  },
  {
    id: 'bell-pepper',
    name: 'Bell Pepper',
    category: 'Vegetables',
    servingSize: '100g',
    calories: 31,
    protein: 1,
    carbs: 6,
    fat: 0.3,
    fiber: 2.1,
    sugar: 4.2,
    sodium: 4,
    tags: ['colorful', 'raw', 'stir-fry'],
    commonPortions: [
      { label: '1 medium (120g)', multiplier: 1.2 },
      { label: '1 large (170g)', multiplier: 1.7 },
    ],
  },
  {
    id: 'lettuce',
    name: 'Lettuce',
    category: 'Vegetables',
    servingSize: '100g',
    calories: 15,
    protein: 1.4,
    carbs: 2.9,
    fat: 0.2,
    fiber: 1.3,
    sugar: 1.8,
    sodium: 28,
    tags: ['green', 'leafy', 'salad', 'base'],
    commonPortions: [
      { label: '1 cup shredded (50g)', multiplier: 0.5 },
      { label: '2 cups (100g)', multiplier: 1 },
    ],
  },
  {
    id: 'onion',
    name: 'Onion',
    category: 'Vegetables',
    servingSize: '100g',
    calories: 40,
    protein: 1.1,
    carbs: 9,
    fat: 0.1,
    fiber: 1.7,
    sugar: 4.2,
    sodium: 4,
    tags: ['aromatic', 'cooked', 'raw'],
    commonPortions: [
      { label: '1/2 medium (60g)', multiplier: 0.6 },
      { label: '1 medium (110g)', multiplier: 1.1 },
    ],
  },
  {
    id: 'potato',
    name: 'Potato',
    category: 'Vegetables',
    servingSize: '100g',
    calories: 77,
    protein: 2,
    carbs: 17,
    fat: 0.1,
    fiber: 2.2,
    sugar: 0.8,
    sodium: 6,
    tags: ['starchy', 'boiled', 'baked', 'mashed'],
    commonPortions: [
      { label: '1 small (170g)', multiplier: 1.7 },
      { label: '1 medium (213g)', multiplier: 2.13 },
      { label: '1 large (300g)', multiplier: 3 },
    ],
  },
  {
    id: 'sweet-potato',
    name: 'Sweet Potato',
    category: 'Vegetables',
    servingSize: '100g',
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
    fiber: 3,
    sugar: 4.2,
    sodium: 55,
    tags: ['orange', 'starchy', 'baked', 'healthy'],
    commonPortions: [
      { label: '1 small (100g)', multiplier: 1 },
      { label: '1 medium (150g)', multiplier: 1.5 },
    ],
  },
  {
    id: 'cauliflower',
    name: 'Cauliflower',
    category: 'Vegetables',
    servingSize: '100g',
    calories: 25,
    protein: 1.9,
    carbs: 5,
    fat: 0.3,
    fiber: 2,
    sugar: 1.9,
    sodium: 30,
    tags: ['white', 'steamed', 'roasted', 'healthy'],
    commonPortions: [
      { label: '1 cup (100g)', multiplier: 1 },
      { label: '2 cups (200g)', multiplier: 2 },
    ],
  },
  {
    id: 'asparagus',
    name: 'Asparagus',
    category: 'Vegetables',
    servingSize: '100g',
    calories: 20,
    protein: 2.2,
    carbs: 3.9,
    fat: 0.1,
    fiber: 2.1,
    sugar: 1.9,
    sodium: 2,
    tags: ['green', 'steamed', 'grilled'],
    commonPortions: [
      { label: '4 spears (60g)', multiplier: 0.6 },
      { label: '8 spears (120g)', multiplier: 1.2 },
    ],
  },
  {
    id: 'zucchini',
    name: 'Zucchini',
    category: 'Vegetables',
    servingSize: '100g',
    calories: 17,
    protein: 1.2,
    carbs: 3.1,
    fat: 0.3,
    fiber: 1,
    sugar: 2.5,
    sodium: 8,
    tags: ['green', 'summer', 'grilled', 'sauteed'],
    commonPortions: [
      { label: '1 small (120g)', multiplier: 1.2 },
      { label: '1 medium (200g)', multiplier: 2 },
    ],
  },
  {
    id: 'mushrooms',
    name: 'Mushrooms',
    category: 'Vegetables',
    servingSize: '100g',
    calories: 22,
    protein: 3.1,
    carbs: 3.3,
    fat: 0.3,
    fiber: 1,
    sugar: 2,
    sodium: 5,
    tags: ['fungi', 'sauteed', 'grilled', 'umami'],
    commonPortions: [
      { label: '1 cup sliced (70g)', multiplier: 0.7 },
      { label: '2 cups (140g)', multiplier: 1.4 },
    ],
  },

  // Grains & Starches
  {
    id: 'rice-white',
    name: 'White Rice (cooked)',
    category: 'Grains',
    servingSize: '100g',
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    fiber: 0.4,
    sugar: 0.1,
    sodium: 1,
    tags: ['staple', 'asian', 'side-dish'],
    commonPortions: [
      { label: '1/2 cup (80g)', multiplier: 0.8 },
      { label: '1 cup (160g)', multiplier: 1.6 },
    ],
  },
  {
    id: 'rice-brown',
    name: 'Brown Rice (cooked)',
    category: 'Grains',
    servingSize: '100g',
    calories: 112,
    protein: 2.6,
    carbs: 24,
    fat: 0.9,
    fiber: 1.8,
    sugar: 0.4,
    sodium: 5,
    tags: ['whole-grain', 'healthy', 'staple'],
    commonPortions: [
      { label: '1/2 cup (80g)', multiplier: 0.8 },
      { label: '1 cup (160g)', multiplier: 1.6 },
    ],
  },
  {
    id: 'pasta-cooked',
    name: 'Pasta (cooked)',
    category: 'Grains',
    servingSize: '100g',
    calories: 131,
    protein: 5,
    carbs: 25,
    fat: 1.1,
    fiber: 1.8,
    sugar: 0.6,
    sodium: 6,
    tags: ['italian', 'staple', 'comfort-food'],
    commonPortions: [
      { label: '1/2 cup (70g)', multiplier: 0.7 },
      { label: '1 cup (140g)', multiplier: 1.4 },
    ],
  },
  {
    id: 'quinoa-cooked',
    name: 'Quinoa (cooked)',
    category: 'Grains',
    servingSize: '100g',
    calories: 120,
    protein: 4.4,
    carbs: 21,
    fat: 1.9,
    fiber: 2.8,
    sugar: 0,
    sodium: 5,
    tags: ['superfood', 'protein-rich', 'healthy'],
    commonPortions: [
      { label: '1/2 cup (90g)', multiplier: 0.9 },
      { label: '1 cup (180g)', multiplier: 1.8 },
    ],
  },
  {
    id: 'bread-white',
    name: 'White Bread',
    category: 'Grains',
    servingSize: '100g (2 slices)',
    calories: 265,
    protein: 9,
    carbs: 49,
    fat: 3.2,
    fiber: 2.7,
    sugar: 5,
    sodium: 491,
    tags: ['sandwich', 'toast', 'breakfast'],
    commonPortions: [
      { label: '1 slice (35g)', multiplier: 0.35 },
      { label: '2 slices (70g)', multiplier: 0.7 },
    ],
  },
  {
    id: 'bread-whole-wheat',
    name: 'Whole Wheat Bread',
    category: 'Grains',
    servingSize: '100g (2 slices)',
    calories: 247,
    protein: 13,
    carbs: 41,
    fat: 3.4,
    fiber: 7,
    sugar: 6,
    sodium: 400,
    tags: ['whole-grain', 'healthy', 'sandwich'],
    commonPortions: [
      { label: '1 slice (35g)', multiplier: 0.35 },
      { label: '2 slices (70g)', multiplier: 0.7 },
    ],
  },
  {
    id: 'oats',
    name: 'Oatmeal (cooked)',
    category: 'Grains',
    servingSize: '100g',
    calories: 68,
    protein: 2.4,
    carbs: 12,
    fat: 1.4,
    fiber: 1.7,
    sugar: 0.5,
    sodium: 49,
    tags: ['breakfast', 'healthy', 'fiber-rich'],
    commonPortions: [
      { label: '1/2 cup (120g)', multiplier: 1.2 },
      { label: '1 cup (240g)', multiplier: 2.4 },
    ],
  },
  {
    id: 'couscous-cooked',
    name: 'Couscous (cooked)',
    category: 'Grains',
    servingSize: '100g',
    calories: 112,
    protein: 3.8,
    carbs: 23,
    fat: 0.2,
    fiber: 1.4,
    sugar: 0.1,
    sodium: 5,
    tags: ['middle-eastern', 'light', 'side-dish'],
    commonPortions: [
      { label: '1/2 cup (80g)', multiplier: 0.8 },
      { label: '1 cup (160g)', multiplier: 1.6 },
    ],
  },

  // Fruits
  {
    id: 'apple',
    name: 'Apple',
    category: 'Fruits',
    servingSize: '100g',
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    fiber: 2.4,
    sugar: 10,
    sodium: 1,
    tags: ['fresh', 'snack', 'healthy'],
    commonPortions: [
      { label: '1 small (150g)', multiplier: 1.5 },
      { label: '1 medium (180g)', multiplier: 1.8 },
      { label: '1 large (220g)', multiplier: 2.2 },
    ],
  },
  {
    id: 'banana',
    name: 'Banana',
    category: 'Fruits',
    servingSize: '100g',
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    fiber: 2.6,
    sugar: 12,
    sodium: 1,
    tags: ['energy', 'snack', 'potassium'],
    commonPortions: [
      { label: '1 small (100g)', multiplier: 1 },
      { label: '1 medium (120g)', multiplier: 1.2 },
      { label: '1 large (135g)', multiplier: 1.35 },
    ],
  },
  {
    id: 'orange',
    name: 'Orange',
    category: 'Fruits',
    servingSize: '100g',
    calories: 47,
    protein: 0.9,
    carbs: 12,
    fat: 0.1,
    fiber: 2.4,
    sugar: 9,
    sodium: 0,
    tags: ['citrus', 'vitamin-c', 'fresh'],
    commonPortions: [
      { label: '1 small (130g)', multiplier: 1.3 },
      { label: '1 medium (150g)', multiplier: 1.5 },
    ],
  },
  {
    id: 'grapes',
    name: 'Grapes',
    category: 'Fruits',
    servingSize: '100g',
    calories: 69,
    protein: 0.7,
    carbs: 18,
    fat: 0.2,
    fiber: 0.9,
    sugar: 15,
    sodium: 2,
    tags: ['snack', 'sweet', 'fresh'],
    commonPortions: [
      { label: '1 cup (150g)', multiplier: 1.5 },
      { label: '1/2 cup (75g)', multiplier: 0.75 },
    ],
  },
  {
    id: 'strawberries',
    name: 'Strawberries',
    category: 'Fruits',
    servingSize: '100g',
    calories: 32,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    fiber: 2,
    sugar: 4.9,
    sodium: 1,
    tags: ['berry', 'antioxidants', 'fresh'],
    commonPortions: [
      { label: '1 cup (150g)', multiplier: 1.5 },
      { label: '1/2 cup (75g)', multiplier: 0.75 },
    ],
  },
  {
    id: 'blueberries',
    name: 'Blueberries',
    category: 'Fruits',
    servingSize: '100g',
    calories: 57,
    protein: 0.7,
    carbs: 14,
    fat: 0.3,
    fiber: 2.4,
    sugar: 10,
    sodium: 1,
    tags: ['berry', 'antioxidants', 'superfood'],
    commonPortions: [
      { label: '1 cup (150g)', multiplier: 1.5 },
      { label: '1/2 cup (75g)', multiplier: 0.75 },
    ],
  },
  {
    id: 'avocado',
    name: 'Avocado',
    category: 'Fruits',
    servingSize: '100g',
    calories: 160,
    protein: 2,
    carbs: 8.5,
    fat: 15,
    fiber: 6.7,
    sugar: 0.7,
    sodium: 7,
    tags: ['healthy-fats', 'creamy', 'superfood'],
    commonPortions: [
      { label: '1/4 avocado (40g)', multiplier: 0.4 },
      { label: '1/2 avocado (80g)', multiplier: 0.8 },
      { label: '1 whole (160g)', multiplier: 1.6 },
    ],
  },

  // Dairy & Alternatives
  {
    id: 'milk-whole',
    name: 'Whole Milk',
    category: 'Dairy',
    servingSize: '100ml',
    calories: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    fiber: 0,
    sugar: 5.1,
    sodium: 43,
    tags: ['calcium', 'beverage'],
    commonPortions: [
      { label: '1 cup (240ml)', multiplier: 2.4 },
      { label: '1/2 cup (120ml)', multiplier: 1.2 },
    ],
  },
  {
    id: 'milk-skim',
    name: 'Skim Milk',
    category: 'Dairy',
    servingSize: '100ml',
    calories: 34,
    protein: 3.4,
    carbs: 5,
    fat: 0.1,
    fiber: 0,
    sugar: 5.1,
    sodium: 41,
    tags: ['low-fat', 'calcium', 'beverage'],
    commonPortions: [
      { label: '1 cup (240ml)', multiplier: 2.4 },
      { label: '1/2 cup (120ml)', multiplier: 1.2 },
    ],
  },
  {
    id: 'yogurt-greek',
    name: 'Greek Yogurt',
    category: 'Dairy',
    servingSize: '100g',
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    fiber: 0,
    sugar: 3.2,
    sodium: 36,
    tags: ['high-protein', 'probiotic', 'breakfast'],
    commonPortions: [
      { label: '1/2 cup (120g)', multiplier: 1.2 },
      { label: '1 cup (240g)', multiplier: 2.4 },
    ],
  },
  {
    id: 'cheese-cheddar',
    name: 'Cheddar Cheese',
    category: 'Dairy',
    servingSize: '100g',
    calories: 402,
    protein: 25,
    carbs: 1.3,
    fat: 33,
    fiber: 0,
    sugar: 0.5,
    sodium: 621,
    tags: ['calcium', 'flavorful'],
    commonPortions: [
      { label: '1 oz (28g)', multiplier: 0.28 },
      { label: '2 oz (56g)', multiplier: 0.56 },
    ],
  },
  {
    id: 'cheese-mozzarella',
    name: 'Mozzarella Cheese',
    category: 'Dairy',
    servingSize: '100g',
    calories: 280,
    protein: 28,
    carbs: 2.2,
    fat: 17,
    fiber: 0,
    sugar: 1,
    sodium: 16,
    tags: ['italian', 'melty', 'pizza'],
    commonPortions: [
      { label: '1 oz (28g)', multiplier: 0.28 },
      { label: '1/4 cup shredded (30g)', multiplier: 0.3 },
    ],
  },
  {
    id: 'butter',
    name: 'Butter',
    category: 'Dairy',
    servingSize: '100g',
    calories: 717,
    protein: 0.9,
    carbs: 0.1,
    fat: 81,
    fiber: 0,
    sugar: 0.1,
    sodium: 11,
    tags: ['cooking', 'flavor', 'fat'],
    commonPortions: [
      { label: '1 tbsp (14g)', multiplier: 0.14 },
      { label: '2 tbsp (28g)', multiplier: 0.28 },
    ],
  },
  {
    id: 'almond-milk',
    name: 'Almond Milk (unsweetened)',
    category: 'Dairy Alternatives',
    servingSize: '100ml',
    calories: 15,
    protein: 0.4,
    carbs: 0.3,
    fat: 1.2,
    fiber: 0.2,
    sugar: 0,
    sodium: 72,
    tags: ['vegan', 'low-calorie', 'plant-based'],
    commonPortions: [
      { label: '1 cup (240ml)', multiplier: 2.4 },
      { label: '1/2 cup (120ml)', multiplier: 1.2 },
    ],
  },

  // Nuts & Seeds
  {
    id: 'almonds',
    name: 'Almonds',
    category: 'Nuts & Seeds',
    servingSize: '100g',
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
    fiber: 12,
    sugar: 4.4,
    sodium: 1,
    tags: ['healthy-fats', 'snack', 'vitamin-e'],
    commonPortions: [
      { label: 'Small handful (23g)', multiplier: 0.23 },
      { label: '1/4 cup (35g)', multiplier: 0.35 },
    ],
  },
  {
    id: 'walnuts',
    name: 'Walnuts',
    category: 'Nuts & Seeds',
    servingSize: '100g',
    calories: 654,
    protein: 15,
    carbs: 14,
    fat: 65,
    fiber: 6.7,
    sugar: 2.6,
    sodium: 2,
    tags: ['omega-3', 'brain-food', 'healthy-fats'],
    commonPortions: [
      { label: 'Small handful (28g)', multiplier: 0.28 },
      { label: '1/4 cup (30g)', multiplier: 0.3 },
    ],
  },
  {
    id: 'peanuts',
    name: 'Peanuts',
    category: 'Nuts & Seeds',
    servingSize: '100g',
    calories: 567,
    protein: 26,
    carbs: 16,
    fat: 49,
    fiber: 8.5,
    sugar: 4.7,
    sodium: 18,
    tags: ['protein', 'snack', 'legume'],
    commonPortions: [
      { label: 'Small handful (28g)', multiplier: 0.28 },
      { label: '1/4 cup (35g)', multiplier: 0.35 },
    ],
  },
  {
    id: 'chia-seeds',
    name: 'Chia Seeds',
    category: 'Nuts & Seeds',
    servingSize: '100g',
    calories: 486,
    protein: 17,
    carbs: 42,
    fat: 31,
    fiber: 34,
    sugar: 0,
    sodium: 16,
    tags: ['superfood', 'omega-3', 'fiber'],
    commonPortions: [
      { label: '1 tbsp (12g)', multiplier: 0.12 },
      { label: '2 tbsp (24g)', multiplier: 0.24 },
    ],
  },
  {
    id: 'sunflower-seeds',
    name: 'Sunflower Seeds',
    category: 'Nuts & Seeds',
    servingSize: '100g',
    calories: 584,
    protein: 21,
    carbs: 20,
    fat: 51,
    fiber: 8.6,
    sugar: 2.6,
    sodium: 9,
    tags: ['vitamin-e', 'snack', 'salad-topper'],
    commonPortions: [
      { label: 'Small handful (28g)', multiplier: 0.28 },
      { label: '2 tbsp (20g)', multiplier: 0.2 },
    ],
  },

  // Prepared Meals & Common Dishes
  {
    id: 'salad-caesar',
    name: 'Caesar Salad',
    category: 'Prepared Meals',
    servingSize: '100g',
    calories: 184,
    protein: 5,
    carbs: 7,
    fat: 15,
    fiber: 2,
    sugar: 2,
    sodium: 300,
    tags: ['salad', 'lunch', 'side'],
    commonPortions: [
      { label: 'Side (150g)', multiplier: 1.5 },
      { label: 'Entree (300g)', multiplier: 3 },
    ],
  },
  {
    id: 'sushi-roll',
    name: 'Sushi Roll (California)',
    category: 'Prepared Meals',
    servingSize: '100g (6 pieces)',
    calories: 140,
    protein: 4,
    carbs: 25,
    fat: 3,
    fiber: 1,
    sugar: 3,
    sodium: 380,
    tags: ['asian', 'seafood', 'rice'],
    commonPortions: [
      { label: '6 pieces (100g)', multiplier: 1 },
      { label: '12 pieces (200g)', multiplier: 2 },
    ],
  },
  {
    id: 'pizza-slice',
    name: 'Pizza Slice (cheese)',
    category: 'Prepared Meals',
    servingSize: '100g (1 slice)',
    calories: 266,
    protein: 11,
    carbs: 33,
    fat: 10,
    fiber: 2,
    sugar: 3,
    sodium: 598,
    tags: ['italian', 'comfort-food', 'cheese'],
    commonPortions: [
      { label: '1 slice (100g)', multiplier: 1 },
      { label: '2 slices (200g)', multiplier: 2 },
      { label: '3 slices (300g)', multiplier: 3 },
    ],
  },
  {
    id: 'burger',
    name: 'Hamburger',
    category: 'Prepared Meals',
    servingSize: '100g',
    calories: 295,
    protein: 17,
    carbs: 24,
    fat: 14,
    fiber: 1,
    sugar: 4,
    sodium: 414,
    tags: ['american', 'beef', 'fast-food'],
    commonPortions: [
      { label: 'Small (150g)', multiplier: 1.5 },
      { label: 'Regular (250g)', multiplier: 2.5 },
    ],
  },
  {
    id: 'french-fries',
    name: 'French Fries',
    category: 'Prepared Meals',
    servingSize: '100g',
    calories: 312,
    protein: 3.4,
    carbs: 41,
    fat: 15,
    fiber: 3.8,
    sugar: 0.3,
    sodium: 246,
    tags: ['side', 'potato', 'fried'],
    commonPortions: [
      { label: 'Small (100g)', multiplier: 1 },
      { label: 'Medium (150g)', multiplier: 1.5 },
      { label: 'Large (200g)', multiplier: 2 },
    ],
  },
  {
    id: 'sandwich-turkey',
    name: 'Turkey Sandwich',
    category: 'Prepared Meals',
    servingSize: '100g',
    calories: 220,
    protein: 14,
    carbs: 28,
    fat: 6,
    fiber: 2,
    sugar: 3,
    sodium: 580,
    tags: ['lunch', 'sandwich', 'poultry'],
    commonPortions: [
      { label: 'Half sandwich (150g)', multiplier: 1.5 },
      { label: 'Whole sandwich (300g)', multiplier: 3 },
    ],
  },
  {
    id: 'soup-chicken-noodle',
    name: 'Chicken Noodle Soup',
    category: 'Prepared Meals',
    servingSize: '100g',
    calories: 53,
    protein: 4,
    carbs: 6,
    fat: 1.5,
    fiber: 0.5,
    sugar: 1,
    sodium: 380,
    tags: ['soup', 'comfort', 'warm'],
    commonPortions: [
      { label: '1 cup (240g)', multiplier: 2.4 },
      { label: '1/2 cup (120g)', multiplier: 1.2 },
    ],
  },
  {
    id: 'pancakes',
    name: 'Pancakes (2)',
    category: 'Prepared Meals',
    servingSize: '100g',
    calories: 227,
    protein: 6,
    carbs: 28,
    fat: 10,
    fiber: 1,
    sugar: 6,
    sodium: 439,
    tags: ['breakfast', 'sweet', 'comfort'],
    commonPortions: [
      { label: '2 pancakes (100g)', multiplier: 1 },
      { label: '3 pancakes (150g)', multiplier: 1.5 },
    ],
  },
  {
    id: 'oatmeal-bowl',
    name: 'Oatmeal Bowl',
    category: 'Prepared Meals',
    servingSize: '100g',
    calories: 68,
    protein: 2.4,
    carbs: 12,
    fat: 1.4,
    fiber: 1.7,
    sugar: 0.5,
    sodium: 49,
    tags: ['breakfast', 'healthy', 'warm'],
    commonPortions: [
      { label: 'Small bowl (200g)', multiplier: 2 },
      { label: 'Medium bowl (300g)', multiplier: 3 },
    ],
  },
  {
    id: 'smoothie-berry',
    name: 'Berry Smoothie',
    category: 'Beverages',
    servingSize: '100ml',
    calories: 55,
    protein: 1.5,
    carbs: 12,
    fat: 0.5,
    fiber: 2,
    sugar: 9,
    sodium: 10,
    tags: ['drink', 'healthy', 'fruit'],
    commonPortions: [
      { label: 'Small (300ml)', multiplier: 3 },
      { label: 'Medium (450ml)', multiplier: 4.5 },
    ],
  },

  // Condiments & Oils
  {
    id: 'olive-oil',
    name: 'Olive Oil',
    category: 'Condiments',
    servingSize: '100ml',
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    sugar: 0,
    sodium: 2,
    tags: ['healthy-fat', 'cooking', 'mediterranean'],
    commonPortions: [
      { label: '1 tsp (5ml)', multiplier: 0.05 },
      { label: '1 tbsp (15ml)', multiplier: 0.15 },
    ],
  },
  {
    id: 'ketchup',
    name: 'Ketchup',
    category: 'Condiments',
    servingSize: '100g',
    calories: 112,
    protein: 1.1,
    carbs: 26,
    fat: 0.2,
    fiber: 0.3,
    sugar: 22,
    sodium: 1114,
    tags: ['tomato', 'sweet', 'condiment'],
    commonPortions: [
      { label: '1 tbsp (15g)', multiplier: 0.15 },
      { label: '2 tbsp (30g)', multiplier: 0.3 },
    ],
  },
  {
    id: 'mayonnaise',
    name: 'Mayonnaise',
    category: 'Condiments',
    servingSize: '100g',
    calories: 680,
    protein: 1,
    carbs: 0.6,
    fat: 75,
    fiber: 0,
    sugar: 0.6,
    sodium: 635,
    tags: ['creamy', 'spread', 'sandwich'],
    commonPortions: [
      { label: '1 tbsp (15g)', multiplier: 0.15 },
      { label: '2 tbsp (30g)', multiplier: 0.3 },
    ],
  },
  {
    id: 'mustard',
    name: 'Mustard',
    category: 'Condiments',
    servingSize: '100g',
    calories: 66,
    protein: 4,
    carbs: 6,
    fat: 3,
    fiber: 4,
    sugar: 1,
    sodium: 1120,
    tags: ['tangy', 'low-calorie', 'sandwich'],
    commonPortions: [
      { label: '1 tsp (5g)', multiplier: 0.05 },
      { label: '1 tbsp (15g)', multiplier: 0.15 },
    ],
  },
  {
    id: 'soy-sauce',
    name: 'Soy Sauce',
    category: 'Condiments',
    servingSize: '100ml',
    calories: 53,
    protein: 3.5,
    carbs: 5,
    fat: 0,
    fiber: 0,
    sugar: 0,
    sodium: 5493,
    tags: ['asian', 'salty', 'umami'],
    commonPortions: [
      { label: '1 tbsp (15ml)', multiplier: 0.15 },
      { label: '2 tbsp (30ml)', multiplier: 0.3 },
    ],
  },
  {
    id: 'honey',
    name: 'Honey',
    category: 'Condiments',
    servingSize: '100g',
    calories: 304,
    protein: 0.3,
    carbs: 82,
    fat: 0,
    fiber: 0.2,
    sugar: 82,
    sodium: 4,
    tags: ['sweet', 'natural', 'tea'],
    commonPortions: [
      { label: '1 tsp (7g)', multiplier: 0.07 },
      { label: '1 tbsp (21g)', multiplier: 0.21 },
    ],
  },
];

// Search function
export function searchFoodDatabase(query: string): FoodDatabaseEntry[] {
  const lowercaseQuery = query.toLowerCase();
  return foodDatabase.filter(
    (food) =>
      food.name.toLowerCase().includes(lowercaseQuery) ||
      food.category.toLowerCase().includes(lowercaseQuery) ||
      food.tags.some((tag) => tag.toLowerCase().includes(lowercaseQuery))
  );
}

// Get food by ID
export function getFoodById(id: string): FoodDatabaseEntry | undefined {
  return foodDatabase.find((food) => food.id === id);
}

// Get foods by category
export function getFoodsByCategory(category: string): FoodDatabaseEntry[] {
  return foodDatabase.filter((food) => food.category === category);
}

// Get all categories
export function getAllCategories(): string[] {
  return [...new Set(foodDatabase.map((food) => food.category))];
}

// Calculate nutrition for a specific portion
export function calculateNutrition(
  foodId: string,
  portionMultiplier: number
): Partial<FoodItem> {
  const food = getFoodById(foodId);
  if (!food) return {};

  return {
    name: food.name,
    quantity: `${Math.round(100 * portionMultiplier)}g`,
    calories: Math.round(food.calories * portionMultiplier),
    protein: Math.round(food.protein * portionMultiplier * 10) / 10,
    carbs: Math.round(food.carbs * portionMultiplier * 10) / 10,
    fat: Math.round(food.fat * portionMultiplier * 10) / 10,
    fiber: Math.round(food.fiber * portionMultiplier * 10) / 10,
    sugar: Math.round(food.sugar * portionMultiplier * 10) / 10,
    sodium: Math.round(food.sodium * portionMultiplier),
  };
}
